title: GitHub Club19   
author: jeningolia
email: sales-enablement@github.com
description: > # this means to ignore newlines until "baseurl:"
  We are so excited to bring you the first ever Club trip. This page is where you'll find all things Club including where we're headed, how to get there, what there is to do, frequently asks questions, and the latest updates. 
# social links

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
