title: GitHub
author: jeningolia
email: sales-enablement@github.com
description: > # this means to ignore newlines until "baseurl:"
Turks and Caicos 
# social links

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
