title: GitHub Club19   
author: jeningolia
email: sales-enablement@github.com
description: > # this means to ignore newlines until "baseurl:"
![hula_loop_octodex03](https://user-images.githubusercontent.com/14840774/53466867-88c0d900-3a08-11e9-96ce-c25e39f5beff.gif)
# social links

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
