title: GitHub Club19   
author: jeningolia
email: sales-enablement@github.com
description: > # this means to ignore newlines until "baseurl:"
<img width="235" alt="screen shot 2017-12-12 at 10 27 44 pm" src="https://user-images.githubusercontent.com/14840774/53467037-274d3a00-3a09-11e9-9155-0d7500676a83.png">

# social links

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
