title: GitHub Club19   
author: jeningolia
email: sales-enablement@github.com
description: > # this means to ignore newlines until "baseurl:"
Turks and Caicos, May 13-17, 2019
# social links

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
